config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :controllers => { :sessions => "users/sessions" }

  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  devise_scope :user do
    root :to => 'users/sessions#new'
  end

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  get 'charts', to: 'charts#index', as: 'chart_index'

  put 'charts/:id/approve', to: 'charts#approve', as: 'approve'

  get '/chart-session', to: 'charts#chart_session'

  post "/charts/export/", to: "charts#export"

  get '/charts/update-entries-session/:id', to: 'charts#update_entries_in_session'

  post "/notifications/mark-as-read/:id", to: "notifications#mark_as_read"

  post "/notifications/mark-all-as-read/", to: "notifications#mark_all_as_read"

  # patch "/charts", to: "charts#create"

  resources :charts

  resources :interventions

  resources :entries

  resources :notifications, only: [:index]

  resources :users do
    get :autocomplete_user_full_name, :on => :collection
    # resources :charts do
    #   resources :interventions
    #   resources :entries
    # end
  end

  get '/clean', to: 'charts#clean_session'

end

app/views/shared/widgets/_available_charts.html.erb
  <section class="col-sm-3 dashboard-panel">
    <button class="btn-slim btn-dark btn-block btn-header">
      <span class="fa fa-bar-chart"></span>
      Make New Chart
    </button>
    <div class="row dashboard-actions">
      <%= link_to "AFP", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "afp".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "ALT", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "alt".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Calcium", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "calcium".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Cholesterol", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "cholesterol".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Copper", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "Copper".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Creatine", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "Creatine".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Diastolic Blood Pressure", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "diastolic_blood_pressure".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Ferritin", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "ferritin".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Folate", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "folate".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Hemoglobin A1C", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "hemoglobin_a1c".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Insulin", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "insulin".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Iron", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "iron".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Mercury", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "mercury".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Red Blood Cell Count", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "red_blood_cell_count".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Systolic Blood Pressure", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "systolic_blood_pressure".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Testosterone", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "testosterone".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "TSH", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "tsh".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Uric Acid", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "uric_acid".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Viral Load", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "viral_load".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Vitamin B12", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "vitamin_b12".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "Vitamin D", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "vitamin_d".classify}), class: "btn btn-slim btn-light btn-block" %>
      <%= link_to "White Blood Cell Count", new_chart_path(:chart => {:user_id => (@user.nil? ? nil : @user.id), :type => "white_blood_cell_count".classify}), class: "btn btn-slim btn-light btn-block" %>
    </div>
  </section>

app/views/shared/widgets/_messages.html.erb
  <section class="col-sm-3 dashboard-panel messages">
    <button class="btn-slim btn-dark btn-block btn-header">
      <span class="fa fa-envelope"></span>
      Messages
      <span class="badge"><%= @messages.count %></span>
    </button>
    <div class="row">
      <div class="panel">
        <%= user_messages(@messages) %>
      </div>
    </div>
  </section>

app/views/shared/widgets/_my_patients.html.erb
  <section class="col-sm-3 dashboard-panel patients">
<!--     <button class="btn-slim btn-dark btn-block btn-header">
      <span class="fa fa-user"></span>
      Patients
    </button> -->
    <!-- <%= link_to "Patient Files", users_path, class: "btn btn-slim btn-light btn-block" %> -->
    <%= link_to users_path, class: "btn btn-slim btn-dark btn-block btn-header" do %>
      <span class="fa fa-user"></span>
      Patients
    <% end %>
    <%= link_to "New Patient", "#", class: "btn btn-slim btn-light btn-block" %>
    <button id="filter-toggler" class="btn btn-slim btn-light btn-block">
      Search / Filter
    </button>
    <div id="filter-widget" class="filter-widget" style="display:none">
      <div class="panel">
        <div class="panel-body">
          <header class="row">
            <h1>Sort by</h1>
            <hr>
          </header>
          <div class="row">
            <select id="patient-sorting">
              <option value="last_name">Surname</option>
              <option value="first_name">First name</option>
              <option value="updated_at">Recent</option>
            </select>
          </div>
          <div class="row">
            <div class="col-xs-12">
              <div class="checkbox">
                <label><input type="checkbox" name="my-patients" value="">My Patients</label>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="checkbox">
                <label><input type="checkbox" name="naturopathic" value="naturopathic">Naturopathic</label>
              </div>
            </div>
            <div class="">
              <div class="">
                <div class="col-xs-6">
                  <div class="checkbox">
                    <label><input type="checkbox" name="pediatric" value="0">Pediatric</label>
                  </div>
                </div>
                <div class="col-xs-6">
                  <div class="checkbox">
                    <label><input type="checkbox" name="adult" value="13">Adult</label>
                  </div>
                </div>
              </div>
            </div>
            <div class="">
              <div class="">
                <div class="col-xs-6">
                  <div class="checkbox">
                    <label><input type="checkbox" name="male" value="m">Male</label>
                  </div>
                </div>
                <div class="col-xs-6">
                  <div class="checkbox">
                    <label><input type="checkbox" name="female" value="f">Female</label>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <select id="chart-filter" multiple  title="By Type of Test" data-live-search="true" data-selected-text-format="count > 3" data-actions-box="true">
              <option data-tokens="afp">AFP</option>
              <option data-tokens="alt">ALT</option>
              <option data-tokens="calcium">Calcium</option>
              <option data-tokens="cholesterol">Cholesterol</option>
              <option data-tokens="copper">Copper</option>
              <option data-tokens="creatine">Creatine</option>
              <option data-tokens="diastolic blood pressure">Diastolic Blood Pressure</option>
              <option data-tokens="ferritin">Ferritin</option>
              <option data-tokens="folate">Folate</option>
              <option data-tokens="hemoglobin a1c">Hemoglobin A1C</option>
              <option data-tokens="insulin">Insulin</option>
              <option data-tokens="iron">Iron</option>
              <option data-tokens="mercury">Mercury</option>
              <option data-tokens="red cell">Red Cell</option>
              <option data-tokens="systolic blood pressure">Systolic Blood Pressure</option>
            </select>
          </div>

        </div>
      </div>
    </div>
    <div class="loader-wrapper hide">
      <div id="loader">
        <div id="top"></div>
        <div id="bottom"></div>
        <div id="line"></div>
      </div>
    </div>
    <ul class="list-unstyled my-patients">
      <% @patients.each do |user| %>
        <li class="patient">
          <%= link_to user_path(user), class: "btn-link" do %>
            <img src="<%= user.avatar %>" alt="<%= user.full_name %>" class=" img-circle" style="">
            <span class="patient-name"><%= "#{user.last_name}, #{user.first_name}" %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </section>

app/views/shared/widgets/_notifications.html.erb
  <section class="col-sm-3 dashboard-panel notifications">
    <button class="btn-slim btn-dark btn-block btn-header">
      <span class="fa fa-bell"></span>
      Notifications
      <span class="badge"><%= @notifications.unread_by(current_user).count %></span>
    </button>
    <div class="row">
      <div class="panel">
        <div class="panel-body">
          <%= user_notifications(@notifications) %>
        </div>
      </div>
    </div>
  </section>